version: "3.4"
services:
  db:
    container_name: prueba
    build: ../database/
    image: pruebaimage:latest
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:root
      - POSTGRES_DB:pruebaps
    ports:
      - 5432:5432
    restart: on-failure
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
networks:
  backend: